// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateAPIKey(arg1) {
  return window['go']['main']['App']['CreateAPIKey'](arg1);
}

export function CreateAccount(arg1) {
  return window['go']['main']['App']['CreateAccount'](arg1);
}

export function CreateGroup(arg1) {
  return window['go']['main']['App']['CreateGroup'](arg1);
}

export function CreateProxy(arg1) {
  return window['go']['main']['App']['CreateProxy'](arg1);
}

export function DeleteAPIKey(arg1) {
  return window['go']['main']['App']['DeleteAPIKey'](arg1);
}

export function DeleteAccount(arg1) {
  return window['go']['main']['App']['DeleteAccount'](arg1);
}

export function DeleteGroup(arg1) {
  return window['go']['main']['App']['DeleteGroup'](arg1);
}

export function DeleteProxy(arg1) {
  return window['go']['main']['App']['DeleteProxy'](arg1);
}

export function GetAccount(arg1) {
  return window['go']['main']['App']['GetAccount'](arg1);
}

export function GetAppVersion() {
  return window['go']['main']['App']['GetAppVersion']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetDashboardStats() {
  return window['go']['main']['App']['GetDashboardStats']();
}

export function GetGroup(arg1) {
  return window['go']['main']['App']['GetGroup'](arg1);
}

export function GetProxy(arg1) {
  return window['go']['main']['App']['GetProxy'](arg1);
}

export function GetProxyAddr() {
  return window['go']['main']['App']['GetProxyAddr']();
}

export function ListAPIKeys() {
  return window['go']['main']['App']['ListAPIKeys']();
}

export function ListAccounts() {
  return window['go']['main']['App']['ListAccounts']();
}

export function ListGroups() {
  return window['go']['main']['App']['ListGroups']();
}

export function ListProxies() {
  return window['go']['main']['App']['ListProxies']();
}

export function ListUsage(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['ListUsage'](arg1, arg2, arg3, arg4, arg5);
}

export function UpdateAccount(arg1) {
  return window['go']['main']['App']['UpdateAccount'](arg1);
}

export function UpdateGroup(arg1) {
  return window['go']['main']['App']['UpdateGroup'](arg1);
}

export function UpdateProxy(arg1) {
  return window['go']['main']['App']['UpdateProxy'](arg1);
}
