// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {model} from '../models';
import {config} from '../models';
import {service} from '../models';

export function CreateAPIKey(arg1:model.APIKey):Promise<void>;

export function CreateAccount(arg1:model.Account):Promise<void>;

export function CreateGroup(arg1:model.Group):Promise<void>;

export function CreateProxy(arg1:model.Proxy):Promise<void>;

export function DeleteAPIKey(arg1:number):Promise<void>;

export function DeleteAccount(arg1:number):Promise<void>;

export function DeleteGroup(arg1:number):Promise<void>;

export function DeleteProxy(arg1:number):Promise<void>;

export function FetchRemotePricing():Promise<number>;

export function GetAccount(arg1:number):Promise<model.Account>;

export function GetAppVersion():Promise<string>;

export function GetConfig():Promise<config.Config>;

export function GetDashboardStats(arg1:string):Promise<model.DashboardStats>;

export function GetGroup(arg1:number):Promise<model.Group>;

export function GetProxy(arg1:number):Promise<model.Proxy>;

export function GetProxyAddr():Promise<string>;

export function HealthCheckAccount(arg1:number,arg2:string):Promise<service.HealthCheckResult>;

export function HealthCheckAllAccounts(arg1:string):Promise<Array<service.HealthCheckResult>>;

export function ListAPIKeys():Promise<Array<model.APIKey>>;

export function ListAccounts():Promise<Array<model.Account>>;

export function ListGroups():Promise<Array<model.Group>>;

export function ListPricing():Promise<Array<model.ModelPricing>>;

export function ListProxies():Promise<Array<model.Proxy>>;

export function ListUsage(arg1:number,arg2:number,arg3:string,arg4:string,arg5:string):Promise<model.UsageListResult>;

export function ListUsageModels():Promise<Array<string>>;

export function ResetPricing():Promise<void>;

export function UpdateAccount(arg1:model.Account):Promise<void>;

export function UpdateGroup(arg1:model.Group):Promise<void>;

export function UpdatePricing(arg1:number,arg2:number,arg3:number,arg4:number,arg5:number):Promise<void>;

export function UpdateProxy(arg1:model.Proxy):Promise<void>;
